/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class FintechModelerApplicationTests {
    @Test
    void contextLoads() {
        // Basic test to ensure Spring context loads
    }
}
